# Generated by Django 5.2 on 2025-04-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('Condition', models.CharField(blank=True, choices=[('acne', 'Acne'), ('eczema', 'Eczema'), ('melasma', 'Melasma'), ('psoriasis', 'Psoriasis'), ('normal', 'Normal')], max_length=10, null=True)),
                ('condition_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
