# Generated by Django 5.2 on 2025-04-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_condition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condition',
            table='condition',
        ),
    ]
