# Generated by Django 5.2 on 2025-04-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_condition_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='Condition',
            new_name='condition',
        ),
    ]
