# Generated by Django 5.2 on 2025-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_condition_customer_modeluser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='modeluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='modeluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='modeluser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='modeluser',
            name='username',
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='modeluser_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
