# Generated by Django 5.2 on 2025-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_condition_model_user_condition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
