# Generated by Django 5.2 on 2025-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_condition_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='condition_image',
        ),
    ]
