# Generated by Django 5.2 on 2025-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_condition_condition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
