# Generated by Django 5.2 on 2025-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_condition_condition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='recommendation',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
