# Generated by Django 5.2 on 2025-04-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_condition_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='recommendation',
        ),
    ]
